### ISSUE TITLE
PHP 7 support?

### ISSUE THREAD

**Issue by lahdekorpi** [purekid/mongodm#91]
The MongoDB extension installed via pecl for PHP 7 has changed a bit and it doesn't work with mongodm anymore. Are there any working branches for a port to the newer mongo lib?

`Class '\Mongo' not found`

That class and `\MongoClient` have been deprecated.
New one is `MongoDB\Driver\Manager` etc.

**Comment by vaseninm** [comment]
Use https://github.com/alcaeus/mongo-php-adapter as compatibility layer

**Comment by purekid** [comment]
Supported.
